<h2>Current Bugs</h2>
<?php echo $this->listToolsForm;?>
<?php
try {
	echo $this->paginationControl($this->paginator,'Sliding','partials/paginationcontrol.phtml');
}catch (Exception $e) {
	echo '<pre>';
	echo $e->getTraceAsString();
	echo '</pre>';
}


?>
<table class='spreadsheet'>
	<tr>
		<th>&nbsp;</th>
		<th>Date</th>
		<th>Priority</th>
		<th>Status</th>
		<th>URL</th>
		<th>Submitter</th>
		<th>Description</th>
	</tr>
	<?php echo $this->partialLoop('bug/table-row.phtml', $this->paginator);?>	
</table>